import { Inter } from 'next/font/google';
import React from 'react';
import SessionProvider from '@/provider/SessionProvider/SessionProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App Title',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <SessionProvider>
          <div className="flex min-h-screen flex-col items-center justify-center text-3xl">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
